version: "3.8"

services:
  backend:
    build: .
    container_name: rag-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

  frontend:
    build: ./rag-frontend
    container_name: rag-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend